# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.IntegerField()),
                ('student_name', models.CharField(max_length=64)),
                ('student_age', models.IntegerField()),
                ('student_semester', models.IntegerField()),
                ('student_career', models.CharField(max_length=64)),
                ('student_image', models.ImageField(upload_to='student_perfil')),
            ],
        ),
    ]
